# Generated by Django 5.1.5 on 2025-02-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='fee',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
